version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Optional if not using Node
    commands:
      - echo "Install phase: No dependencies needed for static site"

  pre_build:
    commands:
      - echo "Pre-build phase: Verifying files"
      - ls -la

  build:
    commands:
      - echo "Build phase: Nothing to compile for HTML/CSS"

  post_build:
    commands:
      - echo "Post-build phase: Files ready for deployment"
      - ls -la

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no

cache:
  paths: []
