version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build phase started"
      - ls -la
  build:
    commands:
      - echo "Build phase started"
      - echo "Building static website..."
  post_build:
    commands:
      - echo "Post-build phase started"
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no

cache:
  paths: [] 