version: 0.2

phases:
  install:
    commands:
      - echo "Install phase: No dependencies needed for HTML/CSS site"

  pre_build:
    commands:
      - echo "Pre-build phase: Listing files"
      - ls -la

  build:
    commands:
      - echo "Build phase: No build step needed for static site"

  post_build:
    commands:
      - echo "Post-build phase: Preparing artifacts"
      - ls -la

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no

cache:
  paths: []
