version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies (if any)..."

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - ls -la

  build:
    commands:
      - echo "Build phase (no build needed for static site)"

  post_build:
    commands:
      - echo "Post-build: preparing for deployment"
      - ls -la

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no

cache:
  paths: []
